apiVersion: v1
kind: Pod
metadata:
  name: mongodb-data
spec:
  volumes:
    - name: mongodb-data
      gcePersistentDisk:
        pdName: test-pv
        fsType: ext4
  containers:
  - image: mongo
    name: mongodb-data
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol:  TCP
